### PR TITLE
2018-2019 pp changes

### PR DESCRIPTION
**Pull request by jamuwu**
from https://github.com/ppy/osu-performance/pull/48

:dab:

### CODE REVIEW

**Comment by Francesco149** [comment]
gotta update the test suite before i can merge this, but thanks

**Comment by peppy** [comment]
Can you include a description of what this is aiming to achieve, along with any assumptions you made along the way?

**Comment by Francesco149** [comment]
rebased to the working test suite, I doubt it's going to pass until the official pp updates and we can rebuild the test suite though

**Comment by Francesco149** [comment]
https://travis-ci.org/Francesco149/pyttanko/jobs/468003630#L908

yea, gotta wait and update the test suite

**Comment by Francesco149** [comment]
oh

i guess i misread that, will fix the other PRs as well

**Comment by 0x61726b** [comment]
Hi, when I run this branch I get inconsistent results with today's update when comparing with (for example star ratings) the osu website. For example [this map](https://osu.ppy.sh/b/1055147) gives me 6.33* but it should be 6.30* according to the website.

**Comment by Francesco149** [comment]
@arkenthera some inaccuracy is normal. this implementation is an approximation as it ignores sliders in favor of simpler, faster code. if it starts getting really inaccurate (like 10%+ error on many maps) I will consider doing a better approximation of sliders.

even if I did implement the same exact logic there would be slight differences due to different implementations of math functions in different languages.

**Pull request merged**
